name: "SoundShare Release"

on:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: ⚙️ Setup
        run: |
          flutter config --enable-windows-desktop
          flutter create --platforms=windows --org com.johirxofficial .

      - name: 📦 Build
        run: flutter build windows --release --pub-version=1.0.0 --build-number=1

      - name: 🤐 Zip
        shell: pwsh
        run: |
          Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath SoundShare_V1.zip

      - name: 🚀 Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          files: SoundShare_V1.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}